development:
  delivery_method: "letter_opener"
  default_url_options:
    host: "example.com"

test:
  delivery_method: "test"
  default_url_options:
    host: "example.com"

production:
  delivery_method: "postmark"
  default_url_options:
    host: "rubyjobs.ru"
  postmark_settings:
    api_key: "y0ur-P0stMarK-ApI-KeY"
